### PR TITLE
Implementation of demonstrations and program generation from them

### PR DESCRIPTION
**Pull request by PetriKalima**
Changes included in demos branch:
-Datarecorder for recording and saving a demonstration
-Implementation of gripper action segmentation
-Greedy trajectory segmentation algorithm
-Globally optimal trajectory segmentation algorithm
-Program creation pipeline combining things listed above
-GUI changes the support everything listed here

### CODE REVIEW

**Comment by MattiaRacca** [comment]
I was trying to solve the merge conflict, but I found something odd in `src/panda_gui/panda_widgets.py`, regarding a certain `self.interface`. It seems that you renamed `self.pbd_interface` to `self.interface` but there are many references to `self.pbd_interface` in there still. Also, `self.interface` is never defined/instantiated, while `self.pbd_interface` is.

@PetriKalima can you commit a fix?

**Comment by PetriKalima** [comment]
Previously, the program creation through GUI was split from the demonstrations as we didn't want to merge the demonstrations yet due to it being unfinished. After this split some changes were made to the program creation through GUI (master branch in my repo). These changes are discussed here [https://github.com/MattiaRacca/eupanda/pull/5](https://github.com/MattiaRacca/eupanda/pull/5). Because of this, the changes, such as renaming self.interface to self.pbd_interface, were not included in the demos branch which was being merged now. This has been changed now and in addition few bugs were fixed.

**Comment by MattiaRacca** [comment]
Hi @PetriKalima, I have manually merged the branches. Could you do a final check if everything looks fine? better if this check in on the robot :)

**Comment by PetriKalima** [comment]
Offline-wise, everything seems fine. I will probably return the laptop to the university next week so hopefully I can do some testing on the robot while I'm there

**Comment by PetriKalima** [comment]
@MattiaRacca I tried doing an online test with the robot but there seemed to be a problem with libfranka when starting the eup interface with roslaunch, the installed version of ros-kinetic-libfranka seems to be 0.8.0
libfrankaproblem

**Comment by MattiaRacca** [comment]
@PetriKalima mmh I don't think this is a problem of eupanda.
When we had that library/update problem in July, we did some reverting to install of libraries to keep using the robot.
However now everything should be fine at the 0.8.0 (you could check which version is installed by doing `apt list ros-kinetic-libfranka ros-kinetic-franka-ros`).
If the packages are at the correct version, you may have still the environment variables (check your .bashrc or list all variables with `printenv`) that tell the software to use the old library (we set them manually at some point). Removing them should do the trick.

**Comment by PetriKalima** [comment]
@MattiaRacca Ok, I'll try by removing the .bashrc line. Is it enough to just restart the pc after removing the line or do I have to manually set the value of FRANKA_DIR again?

**Comment by MattiaRacca** [comment]
@PetriKalima removing the line in the .bashrc, restart, recompile (remove build/devel, then `catkin_make`) should do the trick. `FRANKA_DIR` should not be defined at all, so that the compiler knows that it has to use the library installed system-wise (which should be the 0.8.0, again check that).

**Comment by PetriKalima** [comment]
@MattiaRacca Thanks for the help, I managed to make it work. I found a small bug when converting push motion to linear motion during validation and fixed it. Other than that everything seems to work so I think we can close the pull request

**Pull request merged**
